version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=7753191hD$
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: ./main/
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=7753191hD$
      - POSTGRES_HOST=db

volumes:
  postgres_data:
