# Generated by Django 5.1.3 on 2024-11-22 21:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(default='programmer', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.today)),
                ('private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('archive', 'Заархивирован'), ('active', ' Активный')], default='active', max_length=100)),
                ('users', models.ManyToManyField(through='task_traker.Hiring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hiring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_traker.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[('grooming', 'Grooming'), ('in_progress', 'In Progress'), ('dev', 'Dev'), ('done', 'Done')], default='grooming', max_length=100)),
                ('priority', models.CharField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default='0', max_length=100)),
                ('deadline', models.DateTimeField(default=datetime.datetime.today)),
                ('tester', models.CharField(max_length=1000, null=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_traker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_traker.task')),
            ],
        ),
    ]
